
INSERT INTO location (location_id, si) VALUES
                                           ('11000', '서울특별시'),
                                           ('21000', '부산광역시'),
                                           ('22000', '대구광역시'),
                                           ('23000', '인천광역시'),
                                           ('24000', '광주광역시'),
                                           ('25000', '대전광역시'),
                                           ('26000', '울산광역시'),
                                           ('29000', '세종특별자치시'),
                                           ('31000', '경기도'),
                                           ('32000', '강원도'),
                                           ('33000', '충청북도'),
                                           ('34000', '충청남도'),
                                           ('35000', '전라북도'),
                                           ('36000', '전라남도'),
                                           ('37000', '경상북도'),
                                           ('38000', '경상남도'),
                                           ('39000', '제주특별자치도');

INSERT INTO location (location_id, si) VALUES
                                           (1, '서울'),
                                           (2, '부산'),
                                           (3, '대구'),
                                           (4, '인천'),
                                           (5, '대전'),
                                           (6, '광주'),
                                           (7, '울산');
INSERT INTO tag (tag_id, tag_category, tag_name) VALUES
                                                     (1, 'MBTI', 'none'),
                                                     (2, 'MBTI', 'INFP'),
                                                     (3, 'MBTI', 'ENFP'),
                                                     (4, 'MBTI', 'INTP'),
                                                     (5, 'MBTI', 'ENTP'),
                                                     (6, 'MBTI', 'INFJ'),
                                                     (7, 'MBTI', 'ENFJ'),
                                                     (8, 'MBTI', 'INTJ'),
                                                     (9, 'MBTI', 'ENTJ'),
                                                     (10, 'MBTI', 'ISFP'),
                                                     (11, 'MBTI', 'ESFP'),
                                                     (12, 'MBTI', 'ISTP'),
                                                     (13, 'MBTI', 'ESTP'),
                                                     (14, 'MBTI', 'ISFJ'),
                                                     (15, 'MBTI', 'ESFJ'),
                                                     (16, 'MBTI', 'ISTJ'),
                                                     (17, 'MBTI', 'ESTJ'),
                                                     (18, 'PERSONALITY', '긍정적인'),
                                                     (19, 'PERSONALITY', '체계적인'),
                                                     (20, 'PERSONALITY', '즉흥적인'),
                                                     (21, 'PERSONALITY', '계획적인'),
                                                     (22, 'PERSONALITY', '창의적인'),
                                                     (23, 'PERSONALITY', '감성적인'),
                                                     (24, 'PERSONALITY', '독립적인'),
                                                     (25, 'PERSONALITY', '실질적인'),
                                                     (26, 'PERSONALITY', '사교적인'),
                                                     (27, 'PERSONALITY', '다정한'),
                                                     (28, 'PERSONALITY', '신중한'),
                                                     (29, 'PERSONALITY', '온화한'),
                                                     (30, 'PERSONALITY', '과묵한'),
                                                     (31, 'PERSONALITY', '상냥한'),
                                                     (32, 'PERSONALITY', '솔직한'),
                                                     (33, 'PERSONALITY', '적응을 잘하는'),
                                                     (34, 'PERSONALITY', '표현을 잘하는'),
                                                     (35, 'PERSONALITY', '배려를 잘하는'),
                                                     (36, 'PERSONALITY', '경청을 잘하는'),
                                                     (37, 'PERSONALITY', '상상력이 풍부한'),
                                                     (38, 'PERSONALITY', '도전 정신이 뛰어난'),
                                                     (39, 'PERSONALITY', '재치있는'),
                                                     (40, 'PERSONALITY', '인내심 있는'),
                                                     (41, 'PERSONALITY', '공감 능력이 뛰어난'),
                                                     (42, 'PERSONALITY', '책임감 있는'),
                                                     (43, 'PERSONALITY', '이해가 빠른'),
                                                     (44, 'PERSONALITY', '규칙을 잘 지키는'),
                                                     (45, 'PERSONALITY', '겁이 많은'),
                                                     (46, 'PERSONALITY', '동물을 좋아하는'),
                                                     (47, 'PERSONALITY', '세심한'),
                                                     (48, 'PERSONALITY', '직감이 뛰어난'),
                                                     (49, 'PERSONALITY', '자유로운'),
                                                     (50, 'PERSONALITY', '활발한'),
                                                     (51, 'PERSONALITY', '주도적인'),
                                                     (52, 'PERSONALITY', '호기심 많은'),
                                                     (53, 'PERSONALITY', '적극적인'),
                                                     (54, 'PERSONALITY', '생각이 많은'),
                                                     (55, 'PERSONALITY', '리액션이 많은'),
                                                     (56, 'PERSONALITY', '진지한'),
                                                     (57, 'HOBBY', '여행'),
                                                     (58, 'HOBBY', '캠핑'),
                                                     (59, 'HOBBY', '낚시'),
                                                     (60, 'HOBBY', '게임'),
                                                     (61, 'HOBBY', '보드게임'),
                                                     (62, 'HOBBY', '방탈출'),
                                                     (63, 'HOBBY', '추리게임'),
                                                     (64, 'HOBBY', '쇼핑'),
                                                     (65, 'HOBBY', '심리테스트'),
                                                     (66, 'HOBBY', '사주/타로'),
                                                     (67, 'HOBBY', '뜨개질'),
                                                     (68, 'HOBBY', '재봉'),
                                                     (69, 'HOBBY', '라탄 공예'),
                                                     (70, 'HOBBY', '목공예'),
                                                     (71, 'HOBBY', '가죽공예'),
                                                     (72, 'HOBBY', '보석 십자수'),
                                                     (73, 'HOBBY', '퍼즐'),
                                                     (74, 'HOBBY', '요리'),
                                                     (75, 'HOBBY', '베이킹'),
                                                     (76, 'HOBBY', '홈카페'),
                                                     (77, 'HOBBY', '칵테일'),
                                                     (78, 'HOBBY', '인테리어'),
                                                     (79, 'HOBBY', '독서'),
                                                     (80, 'HOBBY', '자기개발'),
                                                     (81, 'HOBBY', '프로그래밍'),
                                                     (82, 'HOBBY', '블로그'),
                                                     (83, 'HOBBY', '음악 감상'),
                                                     (84, 'HOBBY', '코인노래방'),
                                                     (85, 'HOBBY', '뮤지컬 관람'),
                                                     (86, 'HOBBY', '전시회'),
                                                     (87, 'HOBBY', '연극'),
                                                     (88, 'HOBBY', '공연'),
                                                     (89, 'HOBBY', '밴드'),
                                                     (90, 'HOBBY', '영화보기'),
                                                     (91, 'HOBBY', '드라마보기'),
                                                     (92, 'HOBBY', '유튜브'),
                                                     (93, 'HOBBY', '러닝'),
                                                     (94, 'HOBBY', '배드민턴'),
                                                     (95, 'HOBBY', '테니스'),
                                                     (96, 'HOBBY', '수영'),
                                                     (97, 'HOBBY', '요가'),
                                                     (98, 'HOBBY', '필라테스'),
                                                     (99, 'HOBBY', '등산'),
                                                     (100, 'HOBBY', '산책'),
                                                     (101, 'HOBBY', '홈트'),
                                                     (102, 'HOBBY', '자전거'),
                                                     (103, 'HOBBY', '골프'),
                                                     (104, 'HOBBY', '폴댄스'),
                                                     (105, 'HOBBY', '사진 촬영'),
                                                     (106, 'HOBBY', '글쓰기'),
                                                     (107, 'HOBBY', '캘리그래피'),
                                                     (108, 'HOBBY', '드로잉'),
                                                     (109, 'HOBBY', '수채화'),
                                                     (110, 'HOBBY', '아크릴화'),
                                                     (111, 'HOBBY', '오일파스텔'),
                                                     (112, 'HOBBY', '디지털 드로잉'),
                                                     (113, 'HOBBY', '레진공예'),
                                                     (114, 'HOBBY', '영상편집'),
                                                     (115, 'HOBBY', '포토샵'),
                                                     (116, 'HOBBY', '디자인');
